using System.Globalization;
using System.Text;

namespace HamLoggerEditor.Export;

public enum SqlDialect
{
    SQLite,
    SqlServer
}

public static class CsvExporter
{
    /// <summary>Writes an RFC 4180 CSV file (UTF-8 with BOM so Excel reads accented characters correctly).</summary>
    public static void Save(string path, IReadOnlyList<string> columnNames, IEnumerable<IReadOnlyList<string?>> rows)
    {
        using var writer = new StreamWriter(path, false, new UTF8Encoding(true));
        writer.WriteLine(string.Join(",", columnNames.Select(Quote)));
        foreach (IReadOnlyList<string?> row in rows)
            writer.WriteLine(string.Join(",", row.Select(Quote)));
    }

    private static string Quote(string? value)
    {
        value ??= string.Empty;
        bool needsQuotes = value.IndexOfAny([',', '"', '\r', '\n']) >= 0 || value != value.Trim();
        return needsQuotes ? "\"" + value.Replace("\"", "\"\"") + "\"" : value;
    }
}

public static class SqlScriptExporter
{
    private const int RowsPerBatch = 500;

    /// <summary>
    /// Writes a script that creates the table (if it does not already exist) and inserts every row.
    /// All ADIF values are stored as text; empty values become NULL.
    /// </summary>
    public static void Save(string path, SqlDialect dialect, string tableName,
        IReadOnlyList<string> columnNames, IReadOnlyList<IReadOnlyList<string?>> rows)
    {
        if (!IsValidIdentifier(tableName))
            throw new ArgumentException("Table names may contain only letters, digits and underscores.", nameof(tableName));

        // Pick a name for the surrogate key that does not clash with an ADIF column.
        string idName = "Id";
        while (columnNames.Any(c => c.Equals(idName, StringComparison.OrdinalIgnoreCase))) idName = "Row" + idName;

        using var w = new StreamWriter(path, false, new UTF8Encoding(dialect == SqlDialect.SqlServer));
        w.WriteLine($"-- Generated by HamLogger Contact Editor on {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
        w.WriteLine($"-- {rows.Count:N0} row(s), {columnNames.Count} column(s), target: {(dialect == SqlDialect.SQLite ? "SQLite" : "SQL Server")}");
        w.WriteLine();

        if (dialect == SqlDialect.SQLite) WriteSqlite(w, tableName, idName, columnNames, rows);
        else WriteSqlServer(w, tableName, idName, columnNames, rows);
    }

    public static bool IsValidIdentifier(string name) =>
        !string.IsNullOrWhiteSpace(name) && name.All(c => char.IsAsciiLetterOrDigit(c) || c == '_') && !char.IsAsciiDigit(name[0]);

    private static void WriteSqlite(StreamWriter w, string table, string idName,
        IReadOnlyList<string> cols, IReadOnlyList<IReadOnlyList<string?>> rows)
    {
        string qt = QuoteSqlite(table);
        w.WriteLine("PRAGMA foreign_keys = OFF;");
        w.WriteLine("BEGIN TRANSACTION;");
        w.WriteLine();
        w.WriteLine($"CREATE TABLE IF NOT EXISTS {qt} (");
        w.Write($"    {QuoteSqlite(idName)} INTEGER PRIMARY KEY AUTOINCREMENT");
        foreach (string c in cols) w.Write($",{Environment.NewLine}    {QuoteSqlite(c)} TEXT");
        w.WriteLine();
        w.WriteLine(");");
        w.WriteLine();

        string columnList = string.Join(", ", cols.Select(QuoteSqlite));
        foreach (IReadOnlyList<string?> row in rows)
            w.WriteLine($"INSERT INTO {qt} ({columnList}) VALUES ({string.Join(", ", Values(row, cols.Count, "'"))});");

        w.WriteLine();
        w.WriteLine("COMMIT;");
    }

    private static void WriteSqlServer(StreamWriter w, string table, string idName,
        IReadOnlyList<string> cols, IReadOnlyList<IReadOnlyList<string?>> rows)
    {
        string qt = $"[dbo].{QuoteSqlServer(table)}";

        // Size each column from the data: NVARCHAR(n) where it fits, NVARCHAR(MAX) for long text.
        var widths = new int[cols.Count];
        foreach (IReadOnlyList<string?> row in rows)
            for (int i = 0; i < cols.Count && i < row.Count; i++)
                widths[i] = Math.Max(widths[i], row[i]?.Length ?? 0);

        w.WriteLine("SET NOCOUNT ON;");
        w.WriteLine("SET XACT_ABORT ON;");
        w.WriteLine("GO");
        w.WriteLine();
        w.WriteLine($"IF OBJECT_ID(N'{qt.Replace("'", "''")}', N'U') IS NULL");
        w.WriteLine("BEGIN");
        w.WriteLine($"    CREATE TABLE {qt} (");
        w.Write($"        {QuoteSqlServer(idName)} INT IDENTITY(1,1) NOT NULL PRIMARY KEY");
        for (int i = 0; i < cols.Count; i++)
            w.Write($",{Environment.NewLine}        {QuoteSqlServer(cols[i])} {SqlServerType(widths[i])} NULL");
        w.WriteLine();
        w.WriteLine("    );");
        w.WriteLine("END");
        w.WriteLine("GO");
        w.WriteLine();

        string columnList = string.Join(", ", cols.Select(QuoteSqlServer));
        for (int start = 0; start < rows.Count; start += RowsPerBatch)
        {
            w.WriteLine("BEGIN TRANSACTION;");
            int end = Math.Min(rows.Count, start + RowsPerBatch);
            for (int r = start; r < end; r++)
                w.WriteLine($"INSERT INTO {qt} ({columnList}) VALUES ({string.Join(", ", Values(rows[r], cols.Count, "N'"))});");
            w.WriteLine("COMMIT TRANSACTION;");
            w.WriteLine("GO");
            w.WriteLine();
        }
    }

    private static string SqlServerType(int maxLength)
    {
        if (maxLength > 4000) return "NVARCHAR(MAX)";
        int[] sizes = [50, 100, 255, 1000, 4000];
        return $"NVARCHAR({sizes.First(s => s >= maxLength).ToString(CultureInfo.InvariantCulture)})";
    }

    private static IEnumerable<string> Values(IReadOnlyList<string?> row, int count, string openQuote)
    {
        for (int i = 0; i < count; i++)
        {
            string? v = i < row.Count ? row[i] : null;
            yield return string.IsNullOrEmpty(v) ? "NULL" : openQuote + v.Replace("'", "''") + "'";
        }
    }

    private static string QuoteSqlite(string name) => "\"" + name.Replace("\"", "\"\"") + "\"";

    private static string QuoteSqlServer(string name) => "[" + name.Replace("]", "]]") + "]";
}
